name: Luciano Braga
description: Desenvolvedor Web
meta_description: "Desenvolvedor web Luciano Braga"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: '/'
domain_name: 'https://lucianobragaweb.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://lucianobragaweb.github.io'
author:         'Luciano Braga'
